import type { CoffeeShop } from "@/features/coffee-shop/types/coffee-shop.types";
import { getFacilities } from "@/features/coffee-shop/constants/facilities";

interface MockSeed {
  name: string;
  slug: string;
  address: string;
  rating: number;
  reviewCount: number;
  priceRange: 1 | 2;
  isOpen24Hours: boolean;
  openingTime: string | null;
  closingTime: string | null;
  facilities: string[];
}

const PRICE_LABEL: Record<number, string> = {
  1: "Rp1K - 25K",
  2: "Rp25K - 50K",
};

const DISTRICT = "Sumbersari";

const COORDS: Record<string, { lat: number; lng: number }> = {
  "perasa-coffee-eatery": { lat: -8.1681, lng: 113.7142 },
  "discuss-space-coffee": { lat: -8.1635, lng: 113.7098 },
  "grand-cafe-jember": { lat: -8.1648, lng: 113.7085 },
  "tomoro-coffee-jember": { lat: -8.1652, lng: 113.7079 },
  "kopi-kenangan-sumbersari": { lat: -8.1707, lng: 113.7201 },
  "sumber-redjo": { lat: -8.1719, lng: 113.7223 },
  "hiro-coffee-space": { lat: -8.1593, lng: 113.7036 },
  "vicenzo-coffee": { lat: -8.1601, lng: 113.7048 },
  "888-coffee-more": { lat: -8.1587, lng: 113.7029 },
  "subur-coffee-eatery": { lat: -8.1609, lng: 113.7041 },
  "eterno-coffee": { lat: -8.1664, lng: 113.7167 },
  "kopi-kampus-jember": { lat: -8.1726, lng: 113.7158 },
  "nugas-jember": { lat: -8.1789, lng: 113.7012 },
  "macro-coffee": { lat: -8.1801, lng: 113.7034 },
  "puspa-rasa-kopi": { lat: -8.1815, lng: 113.7058 },
  "kopikuy-jember": { lat: -8.1672, lng: 113.7131 },
  "podo-joyo-coffee": { lat: -8.1903, lng: 113.7246 },
  "alocasia-cafe": { lat: -8.1668, lng: 113.7189 },
  "kopi-samidjoyo": { lat: -8.1659, lng: 113.7118 },
};

const SEEDS: MockSeed[] = [
  {
    name: "Perasa Coffee & Eatery",
    slug: "perasa-coffee-eatery",
    address: "Jl. Sumatra No.128, Tegal Boto Lor",
    rating: 4.7,
    reviewCount: 693,
    priceRange: 2,
    isOpen24Hours: true,
    openingTime: null,
    closingTime: null,
    facilities: ["wifi", "power-outlet", "study-friendly", "indoor", "parking"],
  },
  {
    name: "Discuss Space & Coffee",
    slug: "discuss-space-coffee",
    address: "Jl. Jawa II",
    rating: 4.4,
    reviewCount: 549,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "meeting-area", "indoor", "outdoor"],
  },
  {
    name: "Grand Cafe Jember",
    slug: "grand-cafe-jember",
    address: "Jl. Jawa No.28A",
    rating: 4.4,
    reviewCount: 3411,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "09:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor", "large-capacity"],
  },
  {
    name: "Tomoro Coffee Jember",
    slug: "tomoro-coffee-jember",
    address: "Jl. Jawa No.22",
    rating: 4.7,
    reviewCount: 396,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "08:00",
    closingTime: "22:00",
    facilities: ["air-conditioning", "wifi", "modern-interior"],
  },
  {
    name: "Kopi Kenangan Sumbersari",
    slug: "kopi-kenangan-sumbersari",
    address: "Jl. Kalimantan No.84B",
    rating: 4.4,
    reviewCount: 156,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "08:00",
    closingTime: "22:00",
    facilities: ["grab-and-go", "wifi", "indoor"],
  },
  {
    name: "Sumber Redjo Coffee & Eatery",
    slug: "sumber-redjo",
    address: "Jl. Kalimantan No.37",
    rating: 5.0,
    reviewCount: 203,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "Hiro Coffee and Space",
    slug: "hiro-coffee-space",
    address: "Karimata Area",
    rating: 4.8,
    reviewCount: 204,
    priceRange: 1,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "study-friendly", "indoor"],
  },
  {
    name: "Vicenzo Coffee",
    slug: "vicenzo-coffee",
    address: "Karimata Area",
    rating: 4.6,
    reviewCount: 146,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "888 Coffee & More",
    slug: "888-coffee-more",
    address: "Karimata Square",
    rating: 4.9,
    reviewCount: 280,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "parking"],
  },
  {
    name: "Subur Coffee and Eatery",
    slug: "subur-coffee-eatery",
    address: "Karimata Area",
    rating: 4.4,
    reviewCount: 181,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "Eterno Coffee & Eatery",
    slug: "eterno-coffee",
    address: "Jl. Tidar",
    rating: 4.4,
    reviewCount: 549,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "Kopi Kampus Jember",
    slug: "kopi-kampus-jember",
    address: "Tawangmangu",
    rating: 4.2,
    reviewCount: 500,
    priceRange: 1,
    isOpen24Hours: false,
    openingTime: "07:00",
    closingTime: "03:00",
    facilities: ["wifi", "study-friendly", "indoor"],
  },
  {
    name: "Nugas Jember",
    slug: "nugas-jember",
    address: "Jl. Mastrip 4",
    rating: 4.1,
    reviewCount: 307,
    priceRange: 1,
    isOpen24Hours: true,
    openingTime: null,
    closingTime: null,
    facilities: ["study-friendly", "wifi", "power-outlet"],
  },
  {
    name: "Macro Coffee",
    slug: "macro-coffee",
    address: "Jl. Mastrip Timur",
    rating: 4.7,
    reviewCount: 197,
    priceRange: 1,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "Puspa Rasa Kopi",
    slug: "puspa-rasa-kopi",
    address: "Perumahan Mastrip",
    rating: 4.8,
    reviewCount: 295,
    priceRange: 1,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "KopiKuy Jember",
    slug: "kopikuy-jember",
    address: "Jl. Sumatra VII",
    rating: 4.9,
    reviewCount: 118,
    priceRange: 1,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "study-friendly"],
  },
  {
    name: "Podo Joyo Coffee & Eatery",
    slug: "podo-joyo-coffee",
    address: "Kranjingan",
    rating: 4.7,
    reviewCount: 119,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor", "parking"],
  },
  {
    name: "Alocasia Cafe and Eatery",
    slug: "alocasia-cafe",
    address: "Jl. Riau",
    rating: 4.5,
    reviewCount: 267,
    priceRange: 2,
    isOpen24Hours: false,
    openingTime: "10:00",
    closingTime: "23:00",
    facilities: ["wifi", "indoor", "outdoor"],
  },
  {
    name: "Kopi Samidjoyo",
    slug: "kopi-samidjoyo",
    address: "Jl. Sumatra No.91",
    rating: 4.7,
    reviewCount: 28,
    priceRange: 1,
    isOpen24Hours: true,
    openingTime: null,
    closingTime: null,
    facilities: ["wifi", "indoor"],
  },
];

export const MOCK_COFFEE_SHOPS: CoffeeShop[] = SEEDS.map((seed, index) => ({
  id: `mock-${String(index + 1).padStart(2, "0")}`,
  name: seed.name,
  slug: seed.slug,
  description: null,
  address: seed.address,
  district: DISTRICT,
  latitude: COORDS[seed.slug]?.lat ?? null,
  longitude: COORDS[seed.slug]?.lng ?? null,
  phone: null,
  instagram: null,
  website: null,
  openingTime: seed.openingTime,
  closingTime: seed.closingTime,
  isOpen24Hours: seed.isOpen24Hours,
  priceRange: seed.priceRange,
  priceLabel: PRICE_LABEL[seed.priceRange],
  rating: seed.rating,
  reviewCount: seed.reviewCount,
  verified: true,
  imageUrl: null,
  facilities: getFacilities(seed.facilities),
}));
